server:
  port: 8282
spring:
  application:
    name: user-ops-manager
  datasource:
    driverClassName: org.h2.Driver
    password: 'password'
    username: user
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
 # mvc:
 #   pathmatch:
 #     matching-strategy: ANT_PATH_MATCHER

# Uncomment the following lines if switching to MySQL after commenting above lines
#  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    password: sql-password
#    username: root
#    url: jdbc:mysql://127.0.0.1:3306/dbutf8mb4?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&createDatabaseIfNotExist=true
#
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        show_sql: true

logging:
  level:
    org:
      springframework:
        context: debug

basic:
  auth:
    username: user
    password: password

# Enable debugging logs
debug: false